development:
  adapter: mysql2
  encoding: utf8
  database: i2x
  username: root
  password: 
  host: db
  port: 3306
  pool: 500
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: i2x
  username: i2x
  password: Telematica1234
  host: 127.0.0.1
  port: 5432
  pool: 500
  timeout: 200
  wait_timeout: 300
  reconnect: true
  sslmode: disable
